/**
 * Created by Robert Tatoian on 2/18/2017.
 * @author Robert Tatoian
 * The GUI package contains classes that manage the user interface of the program. Several methods in the contained classes were generated by the Intellij IDE to create the Swing UI.
 */
package GUI;