/**
 * The GUI package contains classes that manage the user interface of the program. Several methods in the contained classes were generated by the Intellij IDE to create the Swing UI.
 * @author Robert Tatoian
 * @since 02/18/2017
 * @version 1.0
 *
 */
package GUI;