package main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;


/**
 * Created by roberttatoian on 2/15/17.
 */
public class UserInterface {

	private JPanel rootPanel;
	private MandelbrotViewer mandelbrotViewer1;
	private JButton savePlot;
	private JButton zoomIn;
	private JButton zoomOut;
	private ImageManager imageManager;

	public UserInterface(ImageManager imageManager) {
		this.imageManager = imageManager;
		JFrame frame = new JFrame("Mandelbrot Set");
		$$$setupUI$$$();
		JFrame.setDefaultLookAndFeelDecorated(true);
		frame.setContentPane(rootPanel);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	private void createUIComponents() {
		mandelbrotViewer1 = new MandelbrotViewer(imageManager);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		rootPanel = new JPanel();
		rootPanel.setLayout(new GridBagLayout());
		rootPanel.setMaximumSize(new Dimension(1024, 1024));
		final JPanel spacer1 = new JPanel();
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		rootPanel.add(spacer1, gbc);
		savePlot = new JButton();
		savePlot.setText("Save Plot");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		rootPanel.add(savePlot, gbc);
		mandelbrotViewer1.setMinimumSize(new Dimension(256, 256));
		mandelbrotViewer1.setPreferredSize(new Dimension(512, 512));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridheight = 3;
		gbc.insets = new Insets(10, 10, 0, 0);
		rootPanel.add(mandelbrotViewer1, gbc);
		zoomIn = new JButton();
		zoomIn.setLabel("+");
		zoomIn.setText("+");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		rootPanel.add(zoomIn, gbc);
		zoomOut = new JButton();
		zoomOut.setLabel("-");
		zoomOut.setText("-");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.NORTH;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		rootPanel.add(zoomOut, gbc);
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.fill = GridBagConstraints.BOTH;
		rootPanel.add(panel1, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
