package main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 * Created by roberttatoian on 2/15/17.
 */
public class UserInterface implements ActionListener {

	private JFrame frame;
	private JPanel rootPanel;
	private MandelbrotViewer mandelbrotViewer1;
	private JButton savePlot;
	private JButton zoomIn;
	private JButton zoomOut;

	private ImageManager imageManager;

	public UserInterface(ImageManager imageManager) {
		this.imageManager = imageManager;
		frame = new JFrame("Mandelbrot Set");
		$$$setupUI$$$();
		JFrame.setDefaultLookAndFeelDecorated(true);
		frame.setContentPane(rootPanel);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);

		zoomIn.setActionCommand("zoomin");
		zoomIn.addActionListener(this);

		zoomOut.setActionCommand("zoomout");
		zoomOut.addActionListener(this);

		savePlot.setActionCommand("save");
		savePlot.addActionListener(this);
	}

	private void createUIComponents() {
		mandelbrotViewer1 = new MandelbrotViewer(imageManager);
	}

	/**
	 * Invoked when an action occurs.
	 *
	 * @param e
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		if ("zoomin".equals(e.getActionCommand())) {
			System.out.print("Zoom In");
		}
		else if ("zoomout".equals(e.getActionCommand())) {
			System.out.print("Zoom Out");
		}
		else if ("save".equals(e.getActionCommand())) {
			//String fileLocation
			//		= (String) JOptionPane.showInputDialog(frame, "Where should the image be written to?", "Save File", JOptionPane.QUESTION_MESSAGE, null, null, null);
			imageManager.writeImage();
		}
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		rootPanel = new JPanel();
		rootPanel.setLayout(new GridBagLayout());
		rootPanel.setMaximumSize(new Dimension(1024, 1024));
		rootPanel.setPreferredSize(new Dimension(512, 512));
		final JPanel spacer1 = new JPanel();
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		rootPanel.add(spacer1, gbc);
		savePlot = new JButton();
		savePlot.setText("Save Plot");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 4;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		rootPanel.add(savePlot, gbc);
		mandelbrotViewer1.setMaximumSize(new Dimension(1000, 1000));
		mandelbrotViewer1.setMinimumSize(new Dimension(256, 256));
		mandelbrotViewer1.setPreferredSize(new Dimension(512, 512));
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridheight = 4;
		gbc.insets = new Insets(10, 10, 0, 0);
		rootPanel.add(mandelbrotViewer1, gbc);
		zoomIn = new JButton();
		zoomIn.setLabel("+");
		zoomIn.setText("+");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		rootPanel.add(zoomIn, gbc);
		zoomOut = new JButton();
		zoomOut.setLabel("-");
		zoomOut.setText("-");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.NORTH;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		rootPanel.add(zoomOut, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
